services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kazi-backend
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    networks:
      - kazi-network
      - web
      - kemo-db-network
      - kemo-minio-network

networks:
  kazi-network:
    driver: bridge
  web:
    external: true
    name: web
  kemo-db-network:
    external: true
    name: kemo-db-network
  kemo-minio-network:
    external: true
    name: kemo-minio-network